#!/bin/bash

calc=$(($(tput cols) / 40 * $(tput lines) / 10))
panes=$((calc > 16 ? 16 : calc))

tmux new -d -s intruder /bin/bash
tmux set-option -g default-shell /bin/bash
tmux set-option status off

for ((i = 1; i < panes; i++)); do
  tmux split-window -t intruder
  tmux select-layout -t intruder tiled
done

tmux attach -t intruder
